### ISSUE TITLE
Problems launching platform first time in my computer

### ISSUE THREAD

**Issue by elchanka** [Protofy-xyz/Protofy#31]
## Expected Behavior
Be able to launch a new fork of Protofy-internal in my computer for the first time.

## Current Behavior
When trying to use yarn to launch the project it reply with an error.

## Steps to Reproduce
1. Prepare the environment (install git, npm)
2. Execute: npm i -g yarn
3. Execute: yarn

## Context (Environment)
- Default setup
- OS: Windows 10
- Browser: none
- Environment: dev

## Issue demo
![image](https://github.com/Protofy-xyz/Protofy/assets/113910381/05d9e399-2133-41c0-aba8-f24a0473e57a)

**Comment by lluis-protofy-xyz** [comment]
Hi @elchanka!

On Windows 10, you need to enable Execution Policies in order to execute Yarn.

You should open PowerShell with administrative permissions and enable them. You can check the current execution policies using the following command:

`Get-ExecutionPolicy -List `

After that, set the correct policy for the current user with the following command:

`Set-ExecutionPolicy RemoteSigned -Scope CurrentUser`

I hope this helps!

**Comment by elchanka** [comment]
Hi Lluis, thanks for your time!
